# Generated by Django 3.2.9 on 2021-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_booking_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
