# Generated by Django 3.2.9 on 2021-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_booking_event_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
