# Generated by Django 3.2.9 on 2022-03-23 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20210705_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pocket',
            name='unique_event',
        ),
        migrations.RemoveField(
            model_name='pocket',
            name='event',
        ),
        migrations.AlterField(
            model_name='pocket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pocketevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='pocketevent',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pocket'),
        ),
    ]
