# Generated by Django 3.2.9 on 2022-03-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220323_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketevent',
            name='pocket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.pocket'),
        ),
    ]
