# Generated by Django 3.2.9 on 2022-03-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_pocketevent_pocket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketevent',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pocket'),
        ),
    ]
