# Generated by Django 3.2.9 on 2022-03-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pocketevent_pocket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocket',
            old_name='user',
            new_name='pocket_user',
        ),
    ]
