# Generated by Django 3.2.9 on 2022-03-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_user_pocket_pocket_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pocketevent',
            constraint=models.UniqueConstraint(fields=('pocket', 'event'), name='unique_event'),
        ),
    ]
