# Generated by Django 3.2 on 2021-04-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('venue', models.TextField(blank=True)),
                ('event_category', models.CharField(choices=[('art_entertain', 'Art & Entertainment'), ('award', 'Award Ceremonie'), ('charity', 'Charity & Fundraiser Event'), ('conert', 'Concert'), ('convention', 'Convention'), ('launch', 'Product Launch'), ('opening', 'Opening Ceremonie'), ('performance', 'Performance'), ('seminar', 'Seminar'), ('sport', 'Sports Event'), ('workshop', 'Workshop'), ('other', 'Other')], max_length=20)),
                ('event_banner_img', models.ImageField(blank=True, upload_to='events_banner')),
                ('featurned', models.BooleanField(default=False)),
                ('last_date', models.DateField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
