# Generated by Django 2.1 on 2021-06-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210423_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventControler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='last_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
        migrations.AddField(
            model_name='eventcontroler',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
