# Generated by Django 2.1 on 2021-06-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210618_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontroler',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
