# Generated by Django 2.1 on 2021-06-20 14:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210619_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 6, 20, 19, 51, 53, 350062), null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
