# Generated by Django 2.1 on 2021-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210620_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
