# Generated by Django 2.1 on 2021-06-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210621_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('art_entertain', 'Art & Entertainment'), ('charity', 'Charity & Fundraising Event'), ('concert', 'Concert'), ('convention', 'Convention'), ('seminar', 'Seminar'), ('sport_outdoor', 'Sports/Outdoor Activity'), ('tech', 'Technology'), ('workshop_education', 'Workshop/Education'), ('other', 'Other')], max_length=20),
        ),
    ]
