# Generated by Django 2.1 on 2021-06-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210621_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_added']},
        ),
    ]
