# Generated by Django 2.1 on 2021-06-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210628_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='events_banner/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(),
        ),
    ]
