# Generated by Django 3.2.9 on 2022-03-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pricing',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
